[phases.setup]
aptPkgs = ["php8.2-mysql", "php8.2-mbstring", "php8.2-xml", "php8.2-bcmath", "php8.2-curl", "php8.2-zip"]

[phases.build]
cmds = [
    "composer install --no-dev",
    "npm ci",
    "npm run build",
    "php artisan optimize",
    "php artisan config:cache",
    "php artisan route:cache",
    "php artisan view:cache"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=${PORT:-8080}"