[phases.setup]
cmds = [
    "apt-get update",
    "apt-get install -y software-properties-common",
    "add-apt-repository -y ppa:ondrej/php",
    "apt-get update",
    "apt-get install -y php8.2 php8.2-mysql php8.2-mbstring php8.2-xml php8.2-bcmath php8.2-curl php8.2-zip php8.2-gd"
]

[phases.build]
cmds = [
    "composer install --optimize-autoloader",
    "npm ci",
    "npm run build",
    "cp .env.railway .env",  # Komentar baris ini untuk menggunakan variabel lingkungan Railway langsung
    "php artisan key:generate --force",  # Generate APP_KEY
    "php artisan storage:link",  # Buat symlink untuk aset statis
    "php artisan config:clear",  # Hapus cache konfigurasi untuk memastikan variabel lingkungan digunakan
    "php artisan config:cache",
    "php artisan route:cache",
    "php artisan view:cache"
]

# Menggunakan Procfile untuk konfigurasi start
# [start]
# cmd = "php artisan serve --host=0.0.0.0 --port=${PORT:-8080}"